### PR TITLE
[BD] Support django major to 1.11

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description 
Support django major to 1.11.
Part of .https://openedx.atlassian.net/browse/BOM-1360

### Reviewers
- [x] @morenol 
- [x]  Is this ready for edX's review? 
- [ ] @jmbowman 
 
### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @andrey-canon! I've created [OSPR-4256](https://openedx.atlassian.net/browse/OSPR-4256) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
LGTM

**Comment by timmc-edx** [comment]
I've merged Travis support to master with https://github.com/edx/django-lang-pref-middleware/pull/5 -- the build is currently broken, but with your changes on this branch + a few linter issues, it should go green for everything. (I did a local merge and test.) I don't think the rebase/merge conflicts should be too bad.

**Comment by andrey-canon** [comment]
@jmbowman  This is ready for another review :D

**Comment by morenol** [comment]
In the release notes, it should be added that the support to python 2.7 was dropped

**Pull request merged**
