### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/teaching-and-learning: I've tagged your team as the owner of this repo. Ok to merge?

**Comment by cahrens** [comment]
Is this repo still used? It looks like @clintonb wrote it 2 years ago, and it hasn't been touched since.

**Comment by clintonb** [comment]
This was made for Insights, the only consumer: https://github.com/edx/edx-analytics-dashboard/blob/2878ef3ccbb3d2db14d7a83984fab3ffab654136/requirements/base.txt#L27. @edx/analytics is the rightful owner.

**Comment by cpennington** [comment]
@edx/analytics: Any objections to taking ownership of this repo?

**Comment by dsjen** [comment]
👍

**Pull request merged**
